### ISSUE TITLE
「プログラマーのための YAML 入門 (検証編) 」yamlファイル埋め込みエラー

### ISSUE THREAD

**Issue by krhitoshi** [rubima/rubima-support#18]
http://magazine.rubyist.net/?0012-YAML

yamlファイルを埋め込んでいると思われる複数箇所にNoMethodErrorが表示されています。
ご報告まで。

```
<p>schema01.yaml : 文字列のシーケンス
<span class="plugin">{{attach_pre('schema01.yaml', 'inline=true')}}</span><strong>NoMethodError (undefined method `escape&#39; for &quot;0012-YAML&quot;:String): inline plugin</strong><br></p>
```

**Comment by gunjisatoshi** [comment]
ご連絡ありがとうございます。attach_pre プラグインで escape メソッドがない、って出てますね。確認します。

**Comment by gunjisatoshi** [comment]
https://github.com/rubima/rubima/issues/297 と同じ問題のようですね。

**Comment by znz** [comment]
https://github.com/rubima/hiki-plugin/commit/51dc31b9a2237762060eb85d8b35561bf4c1fc01 の修正で直ったようなので閉じます。
報告ありがとうございました。
