### ISSUE TITLE
0050-EffectiveRuby_ja%5D の参照

### ISSUE THREAD

**Issue by dogatana** [rubima/rubima-support#20]
index.html から参照(?) されている ./?c=recent 内で

```
<a href="./?0050-EffectiveRuby_ja%5D">
<a href="./?c=diff;p=0050-EffectiveRuby_ja%5D">
```

となっていますが、末尾の%5Dは不要に思います。

これが本当にTypoかどうかわかりませんが、他には類似の参照ががなかったので、念のため
報告させていただきます。

**Comment by znz** [comment]
確認が遅くなりましたが、報告ありがとうございます。
`0050-EffectiveRuby_ja%5D` のページの存在自体が不要っぽい感じだったので、削除しました。

関係者向け追加説明: ログインした時に出てくる編集リンクには `%5D` がついていなかったので手動で追加して、内容を空欄にして削除しました。タイトルは設定されていなくて、キーワードには auth が設定されていたので、公開されていなかったはずなので問題はないはずです。添付ファイルも削除する必要があったので削除しました。
