### ISSUE TITLE
GitHubへのソースコードリンクがズレている

### ISSUE THREAD

**Issue by chiastolite** [rubima/rubima-support#21]
[Rubyist Magazine - 権限管理のgem、Punditの紹介](http://magazine.rubyist.net/?0047-IntroductionToPundit) を読んでいて気付いたのですが、たとえば [Punditの仕組み](http://magazine.rubyist.net/?0047-IntroductionToPundit#l13)のセクションにあるソースコードの行番号へのリンクが本文中に書かれているコードと若干ズレています。

このようにソースコードへリンクする際はtagまたはsha-1を指定するようにポリシーを設定してはどうでしょうか。

**Comment by miyohide** [comment]
@chiastolite ご指摘ありがとうございます。全ソースの確認と修正には時間が掛かりますので、対応には今しばらくお時間をください。
ソースコードへのリンクについては、指針を記します。

**Comment by miyohide** [comment]
@chiastolite ご指摘の件、修正しました。
http://magazine.rubyist.net/?0047-IntroductionToPundit

ご指摘、長い間放置して申し訳ございませんでした。今後もるびまをよろしくお願いします。
