### ISSUE TITLE
0055号の index のリンクがクリック出来ない

### ISSUE THREAD

**Issue by yancya** [rubima/rubima-support#22]
a タグのテキストが抜けてたので、記事へのリンクをクリック出来ない状態でした

https://github.com/yancya/rubima.github.io/blob/fix_link_text_at_0055/articles/0055/0055-index.html

修正してみたんですけど、もしかして rubima.github.io は自動生成の結果で、直接直すものではなかったりしますか？

**Comment by miyohide** [comment]
@yancya ご連絡ありがとうございます。
修正は、 https://github.com/rubima/magazine.rubyist.net のarticles以下にあるものを修正する形となります。お手数おかけしてすみません。

**Comment by yancya** [comment]
やっぱりそんな感じですか。ありがとうございます。あとでやってみます

**Comment by hsbt** [comment]
多分直ってそう...。https://magazine.rubyist.net/articles/0055/0055-index.html の何処のことか把握できなかったので、直ってなかったらまたお願いします。
