### ISSUE TITLE
「RubyKaigi 2019 直前特集号」の冒頭での RubyKaigi 2019 の開催場所の誤り

### ISSUE THREAD

**Issue by msfukui** [rubima/rubima-support#23]
こちらのページを拝見して気が付いたのでお知らせさせてください。

https://magazine.rubyist.net/articles/prerubykaigi2019/preRubyKaigi2019-index.html

冒頭の文章の RubyKaigi 2019 の開催場所の記載が「仙台国際センター」になっているのですが、正しくは「福岡国際会議場」かと思います。

**Comment by miyohide** [comment]
@msfukui ご指摘ありがとうございます。修正しました。
