### ISSUE TITLE
Rubyist のための他言語探訪 【第 14 回】 Whitespace でWhitespaceの仕様が間違っている？

### ISSUE THREAD

**Issue by pocke** [rubima/rubima-support#24]
https://magazine.rubyist.net/articles/0022/0022-Legwork.html

Whitespaceを実装していて気がついたのですが、この記事のWhitespaceの仕様が間違っているようです。
記事中の表2の「数値を読み込みアドレスに格納」の命令が「[tab][newline][tab][newline]」になっていますが、正しくは「[tab][newline][tab]**[tab]**」です。

これはWhitespaceのオリジナルのページで確認できます。(ページが死んでいるので、archiveしか見つけられませんでした。。)
https://web.archive.org/web/20150618184706/http://compsoc.dur.ac.uk/whitespace/tutorial.php

また、 https://ideone.com/ というオンラインコンパイラで試しても、「[tab][newline][tab][tab]」のほうを受け付けるようになっていました。

**Comment by miyohide** [comment]
@pocke ご連絡ありがとうございます。確認しますので、少々お時間をください。

**Comment by miyohide** [comment]
@pocke ご指摘ありがとうございます。反映しました。
https://github.com/rubima/rubima-support/issues/24

**Comment by pocke** [comment]
対応ありがとうございます！
